# Generated by Django 6.0.3 on 2026-03-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cleaning_days',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Длина (м)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Вес (кг)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ширина (м)'),
        ),
        migrations.AddField(
            model_name='service',
            name='cleaning_time',
            field=models.CharField(default='3 дня', help_text='Например: 3 дня, 7-10 дней, от 5 дней', max_length=50, verbose_name='Срок чистки'),
        ),
        migrations.AddField(
            model_name='service',
            name='has_dimensions',
            field=models.BooleanField(default=False, help_text='Для штор, ковров и т.п.', verbose_name='Нужны длина и ширина (м²)'),
        ),
        migrations.AddField(
            model_name='service',
            name='has_weight',
            field=models.BooleanField(default=False, help_text='Для постельного белья и т.п.', verbose_name='Нужен вес (кг)'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_unit',
            field=models.CharField(choices=[('piece', 'За штуку'), ('kg', 'За кг'), ('m2', 'За м²')], default='piece', max_length=10, verbose_name='Единица расчёта'),
        ),
    ]
