# Generated by Django 6.0.3 on 2026-03-04 23:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_service_cleaning_days_orderitem_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'категория услуг',
                'verbose_name_plural': 'категории услуг',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='complexity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='complexity',
            field=models.DecimalField(choices=[(Decimal('1.0'), '1'), (Decimal('1.3'), '1.3'), (Decimal('1.5'), '1.5')], decimal_places=1, default=Decimal('1.0'), max_digits=3, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярная (на главной)'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='core.servicecategory', verbose_name='Категория'),
        ),
    ]
