# Generated by Django 6.0.3 on 2026-03-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicecategory_remove_order_complexity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
