# Generated by Django 6.0.3 on 2026-03-04 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicecategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Если задана — это вариант/подуслуга', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.service', verbose_name='Родительская услуга'),
        ),
    ]
