# Generated by Django 6.0.3 on 2026-03-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicecategory_svg_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='svg_code',
        ),
    ]
