# Generated by Django 6.0.3 on 2026-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_servicecategory_svg_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='svg_code',
            field=models.TextField(blank=True, help_text='Если нет фото, вставьте сюда <svg>...</svg>. Если оба поля пусты, иконки не будет.', null=True, verbose_name='Код SVG иконки'),
        ),
    ]
