# Generated by Django 6.0.3 on 2026-03-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_servicecategory_svg_code_service_svg_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'преимущество (О нас)',
                'verbose_name_plural': 'преимущества (О нас)',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(blank=True, default='С 2020 года', max_length=100, verbose_name='Бейдж в герое')),
                ('hero_title', models.CharField(blank=True, default='Мы — Чисто.Тут', max_length=200, verbose_name='Заголовок героя')),
                ('hero_subtitle', models.TextField(blank=True, default='Профессиональная химчистка в Ижевске. Возвращаем вещам первозданный вид с заботой и вниманием к каждой детали.', verbose_name='Подзаголовок героя')),
                ('years_experience', models.PositiveIntegerField(default=5, verbose_name='Лет опыта (в цифрах)')),
                ('story_title', models.CharField(blank=True, default='Наша история', max_length=200, verbose_name='Заголовок блока «История»')),
                ('story_para1', models.TextField(blank=True, default='«Чисто.Тут» начиналась как небольшая мастерская с одним сотрудником и мечтой — сделать химчистку доступной, честной и по-настоящему качественной. Сегодня мы обслуживаем тысячи клиентов по всему Ижевску.', verbose_name='История, абзац 1')),
                ('story_para2', models.TextField(blank=True, default='Мы используем только профессиональное оборудование ведущих европейских производителей и экологичные составы, которые бережно очищают ткань, сохраняя её цвет, текстуру и форму.', verbose_name='История, абзац 2')),
                ('story_para3', models.TextField(blank=True, default='Каждый заказ проходит тройной контроль качества — от приёмки до выдачи. Мы не отдаём вещь, пока не будем на 100% уверены в результате.', verbose_name='История, абзац 3')),
                ('story_rating_text', models.CharField(blank=True, default='Рейтинг 4.9', max_length=100, verbose_name='Текст «Рейтинг» в карточке')),
                ('story_guarantee_text', models.CharField(blank=True, default='Гарантия на все работы', max_length=200, verbose_name='Текст «Гарантия» в карточке')),
                ('cta_title', models.CharField(blank=True, default='Доверьте нам свои вещи', max_length=200, verbose_name='Заголовок CTA')),
                ('cta_text', models.CharField(blank=True, default='Первый заказ — со скидкой. Попробуйте качество, которое говорит само за себя.', max_length=300, verbose_name='Текст CTA')),
                ('cta_phone', models.CharField(blank=True, default='8 (800) 123-45-67', max_length=50, verbose_name='Телефон в CTA')),
                ('free_delivery_from', models.DecimalField(blank=True, decimal_places=0, default=2000, help_text='Подставляется в текст преимуществ', max_digits=10, null=True, verbose_name='Бесплатная доставка от (₽)')),
            ],
            options={
                'verbose_name': 'страница «О нас»',
                'verbose_name_plural': 'страница «О нас»',
            },
        ),
        migrations.CreateModel(
            name='AboutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='Номер шага')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'шаг процесса (О нас)',
                'verbose_name_plural': 'шаги процесса (О нас)',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
