# Generated by Django 6.0.3 on 2026-03-10 08:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def create_default_delivery_options(apps, schema_editor):
    DeliveryOption = apps.get_model('core', 'DeliveryOption')
    if DeliveryOption.objects.exists():
        return
    DeliveryOption.objects.bulk_create([
        DeliveryOption(
            name='Самовывоз',
            slug='pickup',
            base_price=Decimal('0'),
            free_if_order_total_above=None,
            free_kg=Decimal('0'),
            extra_per_kg=Decimal('0'),
            order=0,
        ),
        DeliveryOption(
            name='Доставка',
            slug='delivery',
            base_price=Decimal('300'),
            free_if_order_total_above=Decimal('2000'),
            free_kg=Decimal('5'),
            extra_per_kg=Decimal('20'),
            order=1,
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_about_page_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='pickup или delivery', max_length=20, unique=True, verbose_name='Slug')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Для доставки — от 300 ₽', max_digits=10, verbose_name='Базовая стоимость (₽)')),
                ('free_if_order_total_above', models.DecimalField(blank=True, decimal_places=0, help_text='Если сумма заказа выше — доставка бесплатно. Пусто для самовывоза.', max_digits=10, null=True, verbose_name='Бесплатно при заказе от (₽)')),
                ('free_kg', models.DecimalField(decimal_places=2, default=Decimal('5'), help_text='Доплата за вес считается после этого порога.', max_digits=6, verbose_name='Бесплатно вес до (кг)')),
                ('extra_per_kg', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=6, verbose_name='Доплата за каждый кг сверх порога (₽)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'способ получения',
                'verbose_name_plural': 'способы получения',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость доставки (₽)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.deliveryoption', verbose_name='Способ получения'),
        ),
        migrations.RunPython(create_default_delivery_options, migrations.RunPython.noop),
    ]
