# Generated by Django 6.0.3 on 2026-03-11 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delivery_option_and_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_method',
            field=models.CharField(choices=[('courier_pickup', 'Курьер заберёт'), ('self_bring', 'Отнесу сам')], default='self_bring', max_length=20, verbose_name='Способ сдачи вещей'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_delivery_requested',
            field=models.BooleanField(default=False, verbose_name='Запрос доставки готового заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.deliveryoption', verbose_name='Способ получения готового заказа'),
        ),
    ]
