# Generated by Django 6.0.3 on 2026-03-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_pickup_method_and_return_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Адрес для курьера'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('web', 'Сайт'), ('staff', 'Сотрудник')], db_index=True, default='staff', max_length=10, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_method',
            field=models.CharField(choices=[('courier_pickup', 'Курьером'), ('self_bring', 'Отнесу сам')], default='self_bring', max_length=20, verbose_name='Способ сдачи вещей'),
        ),
    ]
