# Generated by Django 6.0.3 on 2026-03-11 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_source_and_courier_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличкой курьеру/приемщику'), ('card_on_hand', 'Картой курьеру/приемщику'), ('card_online', 'Картой онлайн'), ('sbp', 'СБП')], default='', max_length=30, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Стоимость забора вещей курьером (₽)'),
        ),
        migrations.AddField(
            model_name='order',
            name='prepayment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Первый взнос (₽)'),
        ),
    ]
