# Generated by Django 6.0.3 on 2026-03-11 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_backfill_payment_method_remove_online_sbp'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Если отзыв оставлен из личного кабинета по выданному заказу.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='core.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличными курьеру или в пункте приёма'), ('card_on_hand', 'Банковской картой курьеру или в пункте приёма')], default='', max_length=30, verbose_name='Способ оплаты'),
        ),
    ]
